### ISSUE TITLE
Broken patch logic for 1.0.0 special case

### ISSUE THREAD

**Issue by HookedBehemoth** [m4xw/emuMMC#12]
Access to album path on 1.0.0 is swapped resulting in an Album folder at the root of the sd card and an emuMMC path on the USER partition.

Mounting the folder via OpenImageDirectoryFileSystem will allow you to mount those exact paths and OFW will write to those.

**Comment by HookedBehemoth** [comment]
Found the fix:
https://github.com/m4xw/emuMMC/pull/13

**Comment by m4xw** [comment]
Obligatory ohno
