### ISSUE TITLE
Installing software to NAND causes an OS crash.

### ISSUE THREAD

**Issue by micktu** [m4xw/emuMMC#19]
Methods employed: 

* **DBI** "Install to NAND"
* **"HOS"** Move software to internal storage" 
* **Game Card Installer** "Nand Install"

A crash stack appears a few gigabytes into transfer pretty consistently. Hekate and Atmo people keep telling me that's an emuMMC issue. Can I help as an engineer?

![103510906-bb428500-4e6e-11eb-89d2-d2f694e8fe70](https://user-images.githubusercontent.com/132598/103762274-b58ca100-5020-11eb-88f0-4287d67ed196.jpeg)

![image](https://user-images.githubusercontent.com/132598/103762242-9ee64a00-5020-11eb-859f-a36c9a18d7f1.png)

**Comment by m4xw** [comment]
2002-3502 happens if you have the 1bit Issue, which is a hardware fault.
Also piracy is not supported.

**Comment by micktu** [comment]
> 2002-3502 happens if you have the 1bit Issue, which is a hardware fault.
> Also piracy is not supported.

Piracy can go lick a rod. Why does 1-biy bug happen on a CFW and does not happen on a HOS? Is there a specific thing blocking the encrypt-copy (as I imagine is what is happening) procedure from working? Can we fix it?

**Comment by m4xw** [comment]
because your sd connector would be at fault, not your eMMC.
The error you encounter is "failed to access eMMC", so that would never happen in OFW, it would be some SD error if any.

Theres your fix 
![image](https://user-images.githubusercontent.com/13141469/103763769-9db21e80-501a-11eb-87ce-94098cc197fc.png)

Depends which pin broke tho.

**Comment by micktu** [comment]
I understand now. Thank you. (It's not mine btw).

**Comment by m4xw** [comment]
Try hekate, make a backup, then go SD Info and check for init/r/w errors
Repeat that 2-3 times and see if anything is non-zero
It's not a foolproof method tho, it is a super sneaky issue. When i had it first it would work for days np, then randomly fail a lot and fix itself.... its really stupid.

As scires said there is a known Issue as well, but I don't think it applies here and you should def. double check if the 1bit issue applies

**Comment by micktu** [comment]
SD copies work perfectly, anything that's bigger than 3GB (pure luck, not a real number) is doomed to fail when installed to internal storage.

**Comment by m4xw** [comment]
Just do it.
I asked for a specific test. The drivers will internally retry, this will show if that happens.

**Comment by m4xw** [comment]
Partition or filebased btw?

**Comment by micktu** [comment]
Got it. As the owner gets home (she's on a plane now) shw eill do it.

Not sure, I did partition then file then a backup. Not sure how it's supposed to be installed.

**Comment by micktu** [comment]
Anyway, the emuMMC is on SD, not NAND. The internal 25Gb are empty.

**Comment by m4xw** [comment]
> 
> 
> Anyway, the emuMMC is on SD, not NAND

If you use emuMMC, everything is on SD obviously, including the internal storage.

**Comment by micktu** [comment]
> If you use emuMMC, everything is on SD obviously, including the internal storage.

Didn't know that. It means that trying to employ NAND is useless. Then it's all OK.

**Comment by m4xw** [comment]
The whole point of emuMMC is making the OS think its accessing the eMMC when its actually using either a partition or a file on SD.
So f.e. moving Data would be moving from "NAND" to SD or vice versa, which would actually be a SD to SD transfer if emuMMC is active.
Double chance to blow up when SD has issues :P

**Comment by m4xw** [comment]
> Try hekate, make a backup, then go SD Info and check for init/r/w errors

Ah, shouldve clarified. I meant a emuMMC backup, so it reads it from SD and writes it to SD.
Afterwards check for r/w/init errors (retries)

**Comment by m4xw** [comment]
and maybe slightly shake it or move it around while doing so, but the issue also happens by just looking at it in my experience...

**Comment by micktu** [comment]
Nah, it's my bad. I don't have a device at hand that I can test on, but I really enjoy Switch homebrew, so poke me if you need programming help. I'm an engineer as well.

(I have a model 2 which does not have RCM as far as I'm aware)
