### ISSUE TITLE
[BUG] Switch crushing after moving game to NAND from settings in file-based EmuNAND 

### ISSUE THREAD

**Issue by rashevskyv** [m4xw/emuMMC#20]
### What's the issue you encountered?

Installing game from eShop, then goes to settings and moving game to NAND with internal HOS method. 
File-based EmuNAND, on **Samsung EVO 128Gb microSD**, formatted with **hekate 5.5.3**. Booted from `hekate =- payloads =- fuse-primary.bin`
Using `atmosphere-0.17.1-master-49f07b06+hbl-2.4.0+hbmenu-3.4.0` from github. I have unpacked `hekate_ctcaer_5.5.3_Nyx_0.9.9.zip` to the root of sd, then unpacked `atmosphere-0.17.1-master-49f07b06+hbl-2.4.0+hbmenu-3.4.0.zip`, renamed `hekate_ctcaer_5.5.3.bin` to `payload.bin` and put `fuse-primary.bin` too `bootloader =- payloads`

My modchip works on Spacecraft-NX. 

### How can the issue be reproduced?

1. Format SВ with hekate 
2. Remove all files from SD
3. Unpack `hekate_ctcaer_5.5.3_Nyx_0.9.9.zip` to the root of sd
4. Unpack `atmosphere-0.17.1-master-49f07b06+hbl-2.4.0+hbmenu-3.4.0.zip`  to the root of sd
5. Renam `hekate_ctcaer_5.5.3.bin` to `payload.bin` 
6. Put `fuse-primary.bin` too `bootloader =- payloads`
7. Launch console
8. `Payloads =- fuse-primary.bin`
9. Install game from eshop
10. Go to **Settings =- Data Management =- Move Data Between Console/microSD Card =- Move to System Memory =- Choose game =- Move Data =- Move**
11.  After approximately 1 minute system will crash with error provided on screenshot below 

![изображение](https://user-images.githubusercontent.com/18294541/105606309-409bc400-5da1-11eb-9e24-30a70670cb47.png)

With fss0 (fss0=atmosphere/fusee-secondary.bin) I got this error:

![изображение](https://user-images.githubusercontent.com/18294541/105625454-2958e700-5e32-11eb-9212-7c8cf15a7d1b.png)

### Crash Report

fuse-primary:
[atmosphere.zip](https://github.com/CTCaer/hekate/files/5860421/atmosphere.zip)

fss0:
[fatal_reports.zip](https://github.com/m4xw/emuMMC/files/5861837/fatal_reports.zip)

### System Firmware Version

11.0.1

### Environment?

Using `atmosphere-0.17.1-master-49f07b06+hbl-2.4.0+hbmenu-3.4.0` from github. I have unpacked `hekate_ctcaer_5.5.3_Nyx_0.9.9.zip` to the root of sd, then unpacked `atmosphere-0.17.1-master-49f07b06+hbl-2.4.0+hbmenu-3.4.0.zip`, renamed `hekate_ctcaer_5.5.3.bin` to `payload.bin` and put `fuse-primary.bin` too `bootloader =- payloads` without additional homebrew, patches or other 

Tested on Switch Light and big Switch on Mariko

### Additional info 

![изображение](https://user-images.githubusercontent.com/18294541/105625457-34ac1280-5e32-11eb-94d0-31107dcf3d3e.png)
![изображение](https://user-images.githubusercontent.com/18294541/105625459-37a70300-5e32-11eb-9de4-0771e6f90e57.png)

**Comment by rashevskyv** [comment]
I got an error even when I am installing game to NAND from eshop
Tried with SanDisk Extreme too

**Comment by urherenow** [comment]
Wait, you're logging into eshop with emunand?

I'd ask what happens if you try booting sysnand without an SD, and installing from eshop, but I don't know you'd even do that with a mod chip installed.

Speaking of which... your mod chip might be the problem. Cold solder joint, stray solder, loose connection to your emmc, you name it...

**Comment by rashevskyv** [comment]
> Speaking of which... your mod chip might be the problem. Cold solder joint, stray solder, loose connection to your emmc, you name it...

No, it cannot. A made more then 20 consoles with Atmosphere and modchip and have this problem on **each**. 
A can boot into SysNAND with stock=1 and try. I am sure there will not be the problem with game installing. I will try 

UPD: no problems without emunand

**Comment by urherenow** [comment]
Also try partition based emunand. That works with SX as well...

**Comment by rashevskyv** [comment]
> Also try partition based emunand. That works with SX as well...

I know that it will works fine. I just trying to report a bug. I am not need to install games to NAND at all, cause I using shrinked NAND on my SD. Just trying to be useful and reporting a bug.

**Comment by m4xw** [comment]
Should be fixed to my knowledge, please reopen if required.
