### ISSUE TITLE
When I am using emuMMC, the Smash Ultimate character CSS go very slow.

### ISSUE THREAD

**Issue by ztf147** [m4xw/emuMMC#24]
### What's the issue you encountered?
When I am using emuMMC, the Smash Ultimate character selecting screen(known as CSS) go very slow.

### How can the issue be reproduced?
Yes, just use emuMMC and open Smash Ultimate to CSS you can see it happen.

it will happen even you have only 8 characters to choose.
It will happen no matter  you have mod or not.
it will happen no matter you overclock or not. 
it will happen I install the game to the NS itself.
It It won't happen in the real system with atmosphere even using mod by using the same SD card with the same soft environment.

### System Firmware Version
NS 13.1 and earlier.
atmosphere 1.2.2 and earlier

### Environment?
not using the Official release, but as I said, it won't happen in real system with atmosphere in the very same environment. 

### Additional context?

This bug may seems no big deal, but you know how often people open this game worldwide, as myself is a mod maker, so my job is to test my mod time and time again and it just killing me every time i test my mod on a switch. so i just really hope this can be solved ,thanks a lot

**Comment by m4xw** [comment]
Is there a diff file based vs partition based for this?

**Comment by ztf147** [comment]
> Is there a diff file based vs partition based for this?

Got that tested, partition based it all OK.
So what now ? should I just change my card to partition based and tell my friends or BBS, or you still want to see that happened to the file based ?   thanks.

**Comment by CTCaer** [comment]
That was probably before fatfs impl or fully fargmented fs. Closing.
