### ISSUE TITLE
emuMMC not working with basic setup

### ISSUE THREAD

**Issue by SeanPerras** [m4xw/emuMMC#26]
Hekate: 5.9.0, Atmosphere: 1.4.0
System FW: 13.2.1

I've been using sysMMC with no issues. I just tried to setup emuMMC and it loads up to the Switch logo and it sits at a back-lit black screen.

I formatted a 128Gb sd card as FAT32 for Atmosphere and partitioned ~30Gb for the emuMMC.

Sorry, if I'm still not asking appropriately, I'm a little new to Github.

**Comment by urherenow** [comment]
Read the docs. Github is for reporting bugs and collaboration, not a help forum. Get help on discord or gbatemp. And nowadays, there is no reason to make a partition-based emuemmc. File-based is much easier to backup/manage.

**Comment by SeanPerras** [comment]
Oh, I apologize. I'll look for that, thanks.
