### ISSUE TITLE
Unicode filename support

### ISSUE THREAD

**Issue by cunhao** [m4xw/emuMMC#29]
Hi,

Thanks a lot for the great project! Please forgive me if this is not the correct repo to discuss this issue described below.

### Issue:
I was trying to transfer a file with Chinese and Japanese in the filename. However, the file will not show in the SD/file browser.

### Environment:
Atmosphere version: 17.0.0
SD card format: FAT32

### Steps to reproduce:
1. Load the file to SD card via Hekate USB tool
1. Boot into emummc
1. Get into GoldLeaf or DBI or Tinfoil
1. Navigate to the location of the file using file/SD browser
1. For Chinese and Japanese filename, the files are simply not listed. A simple filename for testing could be ```你好.txt``` for Chinese and ```こんにちは.txt``` for Japanese.
1. For Korean filename, the file size is 0.0B and the characters are replaced with "_". A filename for testing could be ```안녕하세요.zip```.

Other methods to load the file into SD card have similar results. For example, transferring via DBI will drop the Chinese/Japanese characters in the filename, while scp will reject the operation.

**Comment by SciresM** [comment]
a) this isn't the right project for this
b) this is a Nintendo operating system limitation; they have a bug where they double-decode as utf-8 + shift-jis, making unicode filenames impossible.
