### ISSUE TITLE
Lakka refuses to boot if an emuMMC partition is present

### ISSUE THREAD

**Issue by NickHam13** [m4xw/emuMMC#6]
I tried to boot Lakka, but it wouldn't boot past the hekate splash screen. According to another user, this is fixed by deleting the emuMMC partition. I would like to use Lakka and emuMMC on the same SD card.

**Comment by CTCaer** [comment]
I think that this has to do with hekate setting that partition type as xEE. As it seems, this breaks every linux distro. As I said, I still consider that a bug of linux (not properly reacting to a non existent GPT part), but I will change it in hekate.

**Comment by NickHam13** [comment]
Alright, thanks.
